obs space:
  name: adt_3b_egm2008
  obsdatain:
    engine:
      type: H5File
      obsfile: ${OBS_DIR}/${OBS_PREFIX}adt_3b_egm2008.${OBS_DATE}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: ${DIAG_DIR}/adt_3b_egm2008.${OBS_DATE}.nc4
  simulated variables: [absolute_dynamic_topography]
obs operator:
  name: ADT
obs error:
  covariance model: diagonal
